version: 2.1
executors:
  android-executor:
    docker:
      - image: circleci/openjdk:11-jdk
    working_directory: ~/project
jobs:
  build-apk:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Set up JDK
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-11-jdk
      - run:
          name: Clean Gradle Cache
          command: ./gradlew clean
      - run:
          name: Build APK
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release/app-release.apk
          destination: app-release.apk
workflows:
  version: 2
  build:
    jobs:
      - build-apk